# Change these first
owner: qmutz # Your GitHub organization or username
repo: cicd # Your GitHub repository name

# Add your sites here
sites:
  - name: WP-ADMIN andiegogiap.com
    url: https://andiegogiap.com/blog/wp-admin/
  - name: b00t.xyz BLOG
    url: https://b00t.xyz/blog/
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: b00t.xyz
    url: https://b00t.xyz/wp/
  - name: b00t.xyz
    url: https://b00t.xyz/wp/
  - name: lntel.tk
    url: https://lntel.tk/oc/
  - name: b00t_tk
    url: https://b00t.tk
  - name: lntel.us
    url: https://lntel.us
  - name: lntel.us CMS
    url: https://lntel.us/cms
  - name: BLOG
    url: https://andiegogiap.com/blog
  - name: HEAD
    method: HEAD
    url: https://www.google.com
  - name: Secret Site
    url: $SECRET_SITE
  - name: TCP ping
    url: 68.168.221.170

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: github.com/inteI-cloud
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /cicd
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: cicd
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
